[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "roche_datachapter_lib"
version = "0.0.429"
authors = [{ name = "Lucas Frías", email = "lucasmatiasfrias@live.com" }]
description = "Esta biblioteca de código esta pensada para compartir funcionalidades entre todos los procesos ETL que desarrollemos con Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "setuptools",
    "pkginfo",
    "Flask==3.0.3",
    "Flask-SQLAlchemy==3.0.3",
    "pymysql==1.1.0",
    "pymssql",
    "oracledb==2.2.0",
    "pyodbc==5.0.1",
    "psycopg2-binary==2.9.9",
    "sqlalchemy-redshift==0.8.14",
    "sqlalchemy-hana==1.1.1",
    "pandas==2.1.3",
    "openpyxl==3.1.2",
    "google-api-python-client==2.99.0",
    "google-auth-httplib2==0.1.1",
    "google-auth-oauthlib==1.1.0",
    "chardet==5.2.0",
]

classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"
