[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "roche_datachapter_lib"
version = "0.0.427"
authors = [{ name = "Lucas Frías", email = "lucasmatiasfrias@live.com" }]
description = "Esta biblioteca de código esta pensada para compartir funcionalidades entre todos los procesos ETL que desarrollemos con Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pkginfo",
    "Flask",
    "Flask-SQLAlchemy",
    "pymysql",
    "pymssql",
    "oracledb",
    "pyodbc",
    "psycopg2-binary",
    "sqlalchemy-redshift",
    "sqlalchemy-hana",
    "pandas",
    "openpyxl",
    "google-api-python-client",
    "google-auth-httplib2",
    "google-auth-oauthlib",
    "chardet",
]

classifiers = [
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/pypa/sampleproject"
Issues = "https://github.com/pypa/sampleproject/issues"
