[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
  "IconMatch/*.py",
]

exclude = [
  "*.json",
  "*.png",
]

[project]
name = "IconMatch"
version = "0.0.1"
authors = [
  { name="Piotr Walas", email="piotr.walas@eyegestures.com" },
]
maintainers = [
  { name="Piotr Walas", email="piotr.walas@eyegestures.com" }
]
description = "Package for detecting Icons from images or screen"
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.8"
keywords = ["IconMatch", "NativeSensors", "Icon", "scanning"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/NativeSensors/IconMatch"
Issues = "https://github.com/NativeSensors/IconMatch/Issues"