[project]
name = "arclet-alconna-ariadne"
version = "0.18.3"
authors = [
    { name = "RF-Tar-Railt", email = "rf_tar_railt@qq.com" },
]
dependencies = [
    "arclet-alconna-graia<0.19.0, >= 0.18.3",
    "graia-ariadne<1.0.0, >=0.11.0",
]
description = "Support Alconna to GraiaProject/Ariadne"
readme = "README.md"
requires-python = ">=3.8"
keywords = [
    "alconna",
    "graia",
    "arclet",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: GNU Affero General Public License v3",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[project.license]
text = "AGPL-3.0"

[project.urls]
homepage = "https://github.com/ArcletProject/Alconna-Graia"
repository = "https://github.com/ArcletProject/Alconna-Graia"

[build-system]
requires = [
    "mina-build<0.6",
]
build-backend = "mina.backend"

[tool.mina]
enabled = true

[tool.black]
include = "\\.pyi?$"
line-length = 120
target-version = [
    "py39",
]

[tool.isort]
profile = "black"

[tool.pdm.dev-dependencies]
dev = [
    "editables>=0.3.0",
    "fix-future-annotations>=0.5.0",
    "avilla-console>=0.2.0",
    "avilla-qqapi>=1.0.0a20",
]

[tool.pdm.scripts]
buildall = "pdm mina build --all"
pub = "pdm publish --no-build"

[tool.pdm.scripts.puball]
composite = [
    "buildall",
    "pub",
]

[tool.pdm.build]
includes = [
    "src/arclet/alconna/ariadne",
    ".mina/ariadne.toml",
]
