[tool.poetry]
name = "factorial-aivn-023"
version = "0.1.0"
description = ""
authors = ["Phuc Trinh <trinhduyphuc98@gmail.com>"]
readme = "README.md"
packages = [{include = "factorial_aivn"}]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.34.0"
pytest = "^8.2.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"