[tool.poetry]
name = "smo_rejection"
version = "0.5.6"
description = ""
authors = ["mbtmrw <keks2324098@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
reportlab = "^4.2.0"
openpyxl = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
