[tool.poetry]
name = "fuel-efficiency"
version = "0.1.5"
description = "Fuel efficiency challenge test"
license = "Proprietary"
authors = ["Guilherme Lima <guimarotto@gmail.com>"]
readme = "README.md"
packages = [{include = "fuel_efficiency"}]
classifiers = [
    "Topic :: Software Development",
    "Environment :: Console",
    "Natural Language :: Portuguese (Brazilian)",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.urls]
"CÃ³digo" = "https://github.com/gllima/fuel-efficiency"
"Bug Tracker" = "https://github.com/gllima/fuel-efficiency/issues"

[tool.poetry.dependencies]
python = "^3.12"


[tool.poetry.group.dev.dependencies]
pytest = "^8.2.0"
pytest-cov = "^5.0.0"
blue = "^0.9.1"
isort = "^5.13.2"
taskipy = "^1.12.2"


[tool.poetry.group.docs.dependencies]
mkdocs-material = "^9.5.23"
mkdocstrings = "^0.25.1"
mkdocstrings-python = "^1.10.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "."
addopts = "--doctest-modules"

[tool.isort]
profile = "black"
line_length = 79

[tool.taskipy.tasks]
lint = "blue --check --diff . && isort --check --diff ."
docs = "mkdocs serve"
pre_test = "task lint"
test = "pytest -s -x --cov=fuel_efficiency -vv"
test_entities = "pytest tests/test_entities.py -s -x -vv"
test_entities_raise = "pytest tests/test_entities_raise.py -s -x -vv"
test_algorithms = "pytest tests/test_algorithms.py -s -x -vv"
test_astar = "pytest tests/test_astar.py -s -x -vv"
test_dijkstra = "pytest tests/test_dijkstra.py -s -x -vv"
post_test =  "coverage html"
build = "poetry build"
publish = "poetry publish"