[build-system]
requires = [
    "hatchling",
    "requests"
]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [
    "src/milesToMuppets"
]

[project]
name = "MilesToMuppets"
version = "0.0.1"
authors = [
  { name="Sketched Doughnut", email="author@example.com" },
]
description = "A conversion package to convert Miles to how many songs you can listen to from the Muppets Album"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

# [project.urls]
# Homepage = "https://github.com/pypa/sampleproject"
# Issues = "https://github.com/pypa/sampleproject/issues"