[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "DFPlayer"
version = "0.1.2"
authors = [
  { name="dianudi", email="dian_udi@proton.me" },
]
description = "Python3 library for the DFPlayer-mini"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "pyserial"
]
license = {file = "LICENSE"}
keywords = ["dfplayer", "dfplayer-mini", "mp3-module"]

[project.urls]
Homepage = "https://github.com/dianudi/dfplayer-py"
Issues = "https://github.com/dianudi/dfplayer-py/issues"