[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "AioKafkaEngine"
version = "0.0.3"
authors = [
  { name="Extreme4all", email="author@example.com" },
]
description = "Wrapper around aio-kafka to use and receive via a asyncio queue"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Bot-detector/AioKafkaEngine"
"Bug Tracker" = "https://github.com/Bot-detector/AioKafkaEngine/issues"