[tool.poetry]
name = "ng-data-pipelines-sdk"
version = "0.8.0"
description = "A library for facilitating the development of data engineering pipelines using pyspark. Compatible with MWAA running airflow 2.8.1."
authors = ["ng.cash"]
readme = "README.md"
exclude = [".git/", ".gitignore", "tests/", "docs/", "*.yml", "__pycache__/", "*.pyc", "*.ipynb", "playground/", "poetry.lock", "dist/", "build/"]

[tool.poetry.dependencies]
python = ">=3.9, <3.12"
pyspark = "^3.2.0"
pydantic = "^2.4.2"
boto3 = "^1.28.17"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.4"
ruff = "^0.3.7"
load-dotenv = "^0.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
