[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dmk_packages"
version = "0.7.4"
authors = [{ name = "DataMarketingKorea", email = "infra@datamarketing.co.kr" }]
description = "Common packages for DataMKTKorea"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["SQLAlchemy", "python-dotenv", "psycopg2-binary"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
]

# [project.urls]
# Homepage = ""
# Issues = ""
