[tool.poetry]
name = "smo_rejection"
version = "0.4.1"
description = ""
authors = ["mbtmrw <keks2324098@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
