[tool.poetry]
name = "harken-translation_readers"
version = "0.0.3"
description = "..."
authors = ["Juan Luis Garc√≠a <juanluis1702@gmail.com>"]
readme = "README.md"
packages = [{include = "translation_readers"}]

[tool.poetry.dependencies]
python = ">=3"
poetry = "1.7.1"
funcy = "2.0.0"
# External dependencies
structlog = "23.1.0"
translate-toolkit = "3.13.0"
# Internal dependencies
harken-languages= "*"

[tool]
[tool.black]
line-length = 100
target-version = ["py310"]

[tool.isort]
profile = "black"
known_first_party = ["harken"]

[tool.pyright]
venv = "venv"
reportMissingTypeArgument = true
strictListInference = true

[tool.pylint."messages control"]
ignore = ["setup.py", "__init__.py"]
disable = "all"
enable = ["empty-docstring", "missing-class-docstring", "missing-function-docstring", "missing-module-docstring"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
