[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "arbmaster"
version = "0.1.4"
dependencies = [
  "requests-cache",
  "colorlog",
]
requires-python = ">=3.8"
authors = [
  { name = "Rashoo18" },
]
description = "Odds api automated arbitrage calculator"
readme = "README.md"
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Rashoo18/arbmaster"
Issues = "https://github.com/Rashoo18/arbmaster/issues"