[build-system] 
requires = ["hatchling"] 
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["cfgc"]

[project] 
name = "config-center"
version = "0.0.31"
keywords = ["config", "pipeline", "local", "tool"]
description = "A site-package to create your local pypi-sitepackage, manage your own scripts pack as an env!"
readme = "README.md"
license = {text = "MIT License"}
requires-python = ">= 3.4"
dependencies = [
  "importlib",
  "pathlib",
  "pickle",
  "shutil",
  "os", "sys",
]
authors = [
  {name = "VaterFus", email = "1107818699@qq.com"},
]

[project.urls]
Repository = "https://github.com/WhatMelonGua/config-center"
